### ISSUE TITLE
"Criteria", "Change", and "Comments" sections are deleted when a new comment is added.

### ISSUE THREAD

**Issue by cmilhaupt** [cmilhaupt/audition-web-form#8] opened 2017-07-18 04:47 UTC
If you have the radio button selected or an item from the dropdown menu selected, then click "Add another comment", the criteria dropdown, radio buttons, and typed comments from all previous sections default to empty.

**Comment by VinMags16** [comment] 2017-07-18 13:26
I'm gonna start on this.  The issue is that even though you're using "+=" to append to the html, anytime you set the innerHTML of an element everything inside of it is overwritten.  So even though it's all the same stuff, it's all new entities of the same stuff so the text is no longer there.

**Comment by VinMags16** [comment] 2017-07-18 14:39
Fixed in PR

**Closed by VinMags16** 2017-07-18 14:39 UTC
